language: node_js
node_js:
  - 4.3
  - '6.10'
  - '8.10'
matrix:
  allow_failures:
  - node_js: 4.3
script:
  - npm run lint
  - npm test
  - npm run check-coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
